###  get all users 200 
GET http://localhost:5000/api/users HTTP/1.1


### patch user by id  200
PATCH  http://localhost:5000/api/users/7 HTTP/1.1
Content-Type: application/json

{
  
 
  "tel":"+380905237373",
  "firstName":"Alooo"
  
 
}

### patch user by id  validate
PATCH  http://localhost:5000/api/users/1 HTTP/1.1
Content-Type: application/json

{
  
 
  "tel":"38090523993",
  "firstName":"Alooo",
  "email":"test@test"
  
 
}


###---get /api/users/:userId/phones----------
GET http://localhost:5000/api/users/1/phones HTTP/1.1